name: deuteron
channels:
  - conda-forge
  - defaults
dependencies:
  - cvxpy
  - iminuit
  - pip
  - pytest
  - python=3.8
  - pip:
    - jupyter
    - jupyterlab
    - matplotlib
    - noisyopt
    - numpy
    - openfermion
    - pandas
    - pyyaml
    - qiskit==0.25.0
    - scipy
    - seaborn
    - tqdm
    - qutip
